name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Oracle Java 23
      run: |
        sudo apt update
        sudo apt install -y wget
        wget https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.deb
        sudo dpkg -i jdk-23_linux-x64_bin.deb
        sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-23.0.2-oracle-x64/bin/java 1
        sudo update-alternatives --set java /usr/lib/jvm/jdk-23.0.2-oracle-x64/bin/java

    - name: Verify Java installation
      run: java -version

    - name: Set up Maven
      run: |
        sudo apt update
        sudo apt install -y maven

    - name: Verify Maven installation
      run: mvn -version

    - name: Install MariaDB
      run: |
        sudo apt update
        sudo apt install -y mariadb-server
        sudo service mysql start

    - name: Set up test database
      run: |
        sudo mysql -e "CREATE DATABASE testdb;"
        sudo mysql -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'testpassword';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON testdb.* TO 'testuser'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Set up application.properties
      run: |
        echo "spring.datasource.url=jdbc:mariadb://localhost:3306/testdb" > src/main/resources/application.properties
        echo "spring.datasource.username=testuser" >> src/main/resources/application.properties
        echo "spring.datasource.password=testpassword" >> src/main/resources/application.properties
        echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> src/main/resources/application.properties
        echo "spring.jpa.show-sql=true" >> src/main/resources/application.properties
        echo "spring.jpa.hibernate.ddl-auto=create-drop" >> src/main/resources/application.properties
        echo "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect" >> src/main/resources/application.properties
        echo "spring.jpa.properties.hibernate.format_sql=true" >> src/main/resources/application.properties

    - name: Build and run application
      run: mvn spring-boot:run
